[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roda"
version = "0.1.0"
authors = [
  { name="Nome", email="email@exemplo.com" },
]
description = "Uma biblioteca Python para anÃ¡lises de mobilidade urbana."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
]

dependencies = [
    "pandas",
    "geopandas",
    "numpy",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "seaborn",
    "folium",
    "contextily",
    "geobr",
    "h3",
    "osmnx",
    "gtfs-kit",
    "pandana",
    "tobler",
    "libpysal",
    "rtree",
    "basedosdados",
    "ipeadatapy",
    "jupyterlab",
    "notebook",
    "ipykernel",
    "python-dotenv",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "black",
    "mypy",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
]

[project.urls]
Homepage = "https://github.com/redemobGIT/atlasbr"
Issues = "https://github.com/redemobGIT/atlasbr/issues"

[tool.setuptools]
packages = ["roda"]
package-dir = {"" = "src"}